repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.4  # or the latest
    hooks:
      - id: ruff
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.9.0  # or latest
    hooks:
      - id: mypy

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0  # or latest
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-ast
      - id: debug-statements
      - id: check-merge-conflict
      - id: check-yaml
